# Generated by Django 6.0.6 on 2026-07-02 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_number', models.CharField(blank=True, editable=False, max_length=10, unique=True)),
                ('current_department', models.CharField(choices=[('triage', 'Triage'), ('doctor', 'Doctor'), ('laboratory', 'Laboratory'), ('pharmacy', 'Pharmacy'), ('completed', 'Completed')], default='triage', max_length=20)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('serving', 'Being Served'), ('completed', 'Completed')], default='waiting', max_length=20)),
                ('visit_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='core.patient')),
            ],
        ),
    ]
