# Generated by Django 6.0.6 on 2026-07-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='queue_number',
            field=models.CharField(blank=True, editable=False, max_length=10),
        ),
    ]
