# Generated by Django 6.0.6 on 2026-07-05 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_triage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chief_complaint', models.TextField()),
                ('diagnosis', models.TextField()),
                ('treatment', models.TextField(blank=True)),
                ('prescription', models.TextField(blank=True)),
                ('doctor_notes', models.TextField(blank=True)),
                ('next_department', models.CharField(choices=[('laboratory', 'Laboratory'), ('pharmacy', 'Pharmacy'), ('completed', 'Completed')], max_length=20)),
                ('consultation_date', models.DateTimeField(auto_now_add=True)),
                ('consulted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_consultation', to='core.visit')),
            ],
        ),
    ]
